FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN cp -r frontend/templates/backend/templates
RUN cp -r frontend/static/backend/static
ENV PYTHONPATH=/app
CMD ["flask", "--app", "Expense_Tracker/backend/server.py", "run", "--host=0.0.0.0", "--port=8000"]
