FROM python:3.12-slim
WORKDIR /app
COPY Expense_Tracker/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY Expense_Tracker ./Expense_Tracker
RUN cp -r Expense_Tracker/frontend/templates Expense_Tracker/backend/templates
RUN cp -r Expense_Tracker/frontend/static Expense_Tracker/backend/static
ENV PYTHONPATH=/app
CMD ["flask", "--app", "Expense_Tracker/backend/server.py", "run", "--host=0.0.0.0", "--port=8000"]
